-- Actuarial insurance portfolio database schema.
-- Domain: portfolio, policy, premium, and claim data used for actuarial loss-ratio analysis.

DROP TABLE IF EXISTS claims;
DROP TABLE IF EXISTS premium_payments;
DROP TABLE IF EXISTS policies;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS insurance_products;

CREATE TABLE insurance_products (
    product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code VARCHAR(20) NOT NULL UNIQUE,
    product_name VARCHAR(100) NOT NULL,
    line_of_business VARCHAR(30) NOT NULL,
    base_annual_premium NUMERIC(12,2) NOT NULL CHECK (base_annual_premium > 0),
    launch_date DATE NOT NULL
);

CREATE TABLE customers (
    customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_code VARCHAR(20) NOT NULL UNIQUE,
    full_name VARCHAR(100) NOT NULL,
    birth_date DATE NOT NULL,
    region VARCHAR(40) NOT NULL,
    occupation VARCHAR(80) NOT NULL,
    risk_score INTEGER NOT NULL CHECK (risk_score BETWEEN 1 AND 100)
);

CREATE TABLE policies (
    policy_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_number VARCHAR(30) NOT NULL UNIQUE,
    customer_id INTEGER NOT NULL REFERENCES customers(customer_id),
    product_id INTEGER NOT NULL REFERENCES insurance_products(product_id),
    policy_start_date DATE NOT NULL,
    policy_end_date DATE NOT NULL,
    insured_amount NUMERIC(14,2) NOT NULL CHECK (insured_amount > 0),
    annual_premium NUMERIC(12,2) NOT NULL CHECK (annual_premium > 0),
    status VARCHAR(20) NOT NULL CHECK (status IN ('active', 'expired', 'lapsed')),
    CHECK (policy_end_date > policy_start_date)
);

CREATE TABLE premium_payments (
    payment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id INTEGER NOT NULL REFERENCES policies(policy_id),
    payment_date DATE NOT NULL,
    paid_amount NUMERIC(12,2) NOT NULL CHECK (paid_amount > 0),
    payment_method VARCHAR(30) NOT NULL,
    payment_status VARCHAR(20) NOT NULL CHECK (payment_status IN ('paid', 'late', 'refunded'))
);

CREATE TABLE claims (
    claim_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id INTEGER NOT NULL REFERENCES policies(policy_id),
    claim_number VARCHAR(30) NOT NULL UNIQUE,
    claim_date DATE NOT NULL,
    claim_type VARCHAR(50) NOT NULL,
    claim_amount NUMERIC(12,2) NOT NULL CHECK (claim_amount > 0),
    paid_amount NUMERIC(12,2) NOT NULL CHECK (paid_amount >= 0),
    claim_status VARCHAR(20) NOT NULL CHECK (claim_status IN ('open', 'approved', 'rejected', 'paid')),
    CHECK (paid_amount <= claim_amount)
);
